// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var apiResourcesOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--api-group", Description: "Limit to resources in the specified API group."},
	prompt.Suggest{Text: "--cached", Description: "Use the cached list of resources if available."},
	prompt.Suggest{Text: "--namespaced", Description: "If false, non-namespaced resources will be returned, otherwise returning namespaced resources by default."},
	prompt.Suggest{Text: "--no-headers", Description: "When using the default or custom-column output format, don't print headers (default print headers)."},
	prompt.Suggest{Text: "-o", Description: "Output format. One of: wide|name."},
	prompt.Suggest{Text: "--output", Description: "Output format. One of: wide|name."},
	prompt.Suggest{Text: "--verbs", Description: "Limit to resources that support the specified verbs."},
}
