// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var authCanIOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--all-namespaces", Description: "If true, check the specified action in all namespaces."},
	prompt.Suggest{Text: "-q", Description: "If true, suppress output and just return the exit code."},
	prompt.Suggest{Text: "--quiet", Description: "If true, suppress output and just return the exit code."},
	prompt.Suggest{Text: "--subresource", Description: "SubResource such as pod/log or deployment/scale"},
}
