// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var versionOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--client", Description: "Client version only (no server required)."},
	prompt.Suggest{Text: "-o", Description: "One of 'yaml' or 'json'."},
	prompt.Suggest{Text: "--output", Description: "One of 'yaml' or 'json'."},
	prompt.Suggest{Text: "--short", Description: "Print just the version number."},
}
